### ISSUE TITLE
`one change version` fail when no `changes` in config

### ISSUE THREAD

**Issue by alecmev** [paularmstrong/onerepo#677]
### What version of oneRepo are you using?

1.1.0

### Environment info

```sh
Not relevant.
```

### Command

one change version

### What did you expect to happen?

No errors.

### What actually happened?

```
TypeError: Cannot read properties of undefined (reading 'formatting')
```

The source is this:

https://github.com/paularmstrong/onerepo/blob/f77209731674a8fd0286bd0a8c0cf2eced952ba1/modules/onerepo/src/core/changes/version.ts#L74

`config` is typed as `Required<RootConfig>`, but it's actually raw user config:

https://github.com/paularmstrong/onerepo/blob/f77209731674a8fd0286bd0a8c0cf2eced952ba1/modules/onerepo/src/setup/setup.ts#L137

Should it be `config: resolvedConfig` perhaps?

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by paularmstrong** [comment]
> Should it be config: resolvedConfig perhaps?

A couple of us hit this issue before but totally missed this. Thanks! I'm not sure how that slipped through the cracks.
