### ISSUE TITLE
`one graph verify` doesn't force latest local version

### ISSUE THREAD

**Issue by alecmev** [paularmstrong/onerepo#678]
### What version of oneRepo are you using?

1.1.0

### Environment info

```sh
Not relevant.
```

### Command

one graph verify --mode strict

### What did you expect to happen?

This to not pass:

```json
{
  "name": "@acme/foo",
  "version": "2.0.0"
}
```

```json
{
  "name": "@acme/bar",
  "version": "2.0.0",
  "dependencies": {
    "@acme/foo": "1.0.0"
  }
}
```

### What actually happened?

Verification passes. I'm having trouble imagining legitimate cases where such a version mismatch would be desired. I'm currently using the following Yarn constraint to cover this (in case you're familiar):

```prolog
gen_enforced_dependency(WorkspaceCwd, DependencyIdent, DependencyRange2, DependencyType) :-
  workspace_has_dependency(WorkspaceCwd, DependencyIdent, DependencyRange, DependencyType),
  DependencyRange \= 'workspace:*',
  workspace_ident(DependencyCwd, DependencyIdent),
  workspace_version(DependencyCwd, DependencyRange2),
  DependencyRange \= DependencyRange2.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by paularmstrong** [comment]
I can't repro this. Can you provide a repro?

```
one graph verify --mode strict
 ┌ Validating dependency trees
 │ ERR Version mismatches found in "onerepo"
 │ ERR  ↳ Dependency "@onerepo/file@1.0.0" expected to match "1.0.1" from Workspace dependency "@onerepo/git"
 └ ✘ 3ms
// ...
```

**Comment by alecmev** [comment]
Sure! [Here](https://github.com/alecmev/onerepo-repro-678). Run `yarn`, change `"@acme/foo": "2.0.0"` to `"@acme/foo": "1.0.0"` in `packages/bar/package.json`, run `yarn one graph verify --mode strict`.

**Comment by alecmev** [comment]
Since `workspace:*` gets replaced with the correct version when published, as you mentioned in #679, maybe the solution to this issue would be to just require `workspace:*` (or `workspace:^`) everywhere?

**Comment by paularmstrong** [comment]
It could, but that's dependent on the package manager -- npm doesn't support the workspace protocol. 

If anything, I would probably opt to switch and _not_ use the workspace protocol at all, as I've seen people not fully able to grok what it means and I'd rather keep things simple. 

Happy to discuss further and come to a consensus if you feel strongly one way or another.

**Comment by alecmev** [comment]
Nah, I'm with you on this, explicit versions are more portable. As long as the consistency is enforced and they're auto-updated, which they are, then there's no downside.
