### ISSUE TITLE
`one graph verify` lets public packages have `workspace:*` dependencies

### ISSUE THREAD

**Issue by alecmev** [paularmstrong/onerepo#679]
### What version of oneRepo are you using?

1.1.0

### Environment info

```sh
Not relevant.
```

### Command

one graph verify --mode strict

### What did you expect to happen?

This to not pass:

```json
{
  "name": "@acme/foo",
  "version": "1.0.0"
}
```

```json
{
  "name": "@acme/bar",
  "version": "1.0.0",
  "dependencies": {
    "@acme/foo": "workspace:*"
  }
}
```

### What actually happened?

Verification passes. I think this is a mistake in 100% of cases, unless `@acme/bar` is private. Yarn constraints (reading them now, I see that they're a bit sloppy, but that's why I want to get rid of them):

```prolog
gen_enforced_dependency(WorkspaceCwd, DependencyIdent, DependencyRange, DependencyType) :-
  \+ workspace_field(WorkspaceCwd, 'private', _),
  workspace_has_dependency(WorkspaceCwd, DependencyIdent, 'workspace:*', DependencyType),
  workspace_ident(DependencyCwd, DependencyIdent),
  \+ workspace_field(DependencyCwd, 'private', 'true'),
  workspace_version(DependencyCwd, DependencyRange).

gen_enforced_dependency(WorkspaceCwd, DependencyIdent, DependencyRange, DependencyType) :-
  workspace_field(WorkspaceCwd, 'version', _),
  workspace_has_dependency(WorkspaceCwd, DependencyIdent, 'workspace:*', DependencyType),
  DependencyType \= 'devDependencies',
  workspace_ident(DependencyCwd, DependencyIdent),
  workspace_version(DependencyCwd, DependencyRange).
```

If this is implemented then the case of public packages depending on private ones is covered automatically, as long as the `version` field isn't allowed in private `package.json`. Which can be overridden with a custom graph schema. Is that something to worry about? Or is that "at your own risk" territory?

Just in case, `devDependencies` shouldn't have these restrictions.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by paularmstrong** [comment]
Yes, that's okay. When versioning, any production dependency version will be swapped with the current (or new) version.

**Comment by alecmev** [comment]
I see, that also works, thanks! However, that means "public depending on private" isn't covered:

```json
{
  "name": "@acme/foo",
  "private": true
}
```

```json
{
  "name": "@acme/bar",
  "version": "1.0.0",
  "dependencies": {
    "@acme/foo": "workspace:*"
  }
}
```

The above passes the verification. I imagine it might blow up if I try publishing it, but I would like this problem to be reported earlier, during regular automatic checks.

**Comment by paularmstrong** [comment]
Oh okay, _that_ seems like a different issue that was never accounted for. 

We should make public packages not able to require private packages as production & peer dependencies. I'll file a separate issue for that.

**Comment by paularmstrong** [comment]
#682
