### ISSUE TITLE
The website home page has rendering performance issues

### ISSUE THREAD

**Issue by unadlib** [paularmstrong/onerepo#681]
### Environment info

```sh
Chrome v123.0.6312.58
```

### Command

none

### What did you expect to happen?

none

### What actually happened?

The Onerepo.tools website has rendering performance issues

<img width="1151" alt="image" src="https://github.com/paularmstrong/onerepo/assets/18650460/02add586-d717-45b3-a0cd-89499adf82d4">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by paularmstrong** [comment]
This may be system/machine dependent. I'm on a Mac M3 Pro and getting 120fps, Chromium Engine Version 123.0.6312.87

![Screenshot 2024-03-30 at 08 36 02](https://github.com/paularmstrong/onerepo/assets/33297/b0653394-9220-4800-8dda-6f4f8e471858)

**Comment by paularmstrong** [comment]
Also tested Chrome 123 on a 2019 Intel Quad Core 2.4GHz Macbook and saw no stutter with 60fps

**Comment by paularmstrong** [comment]
Happy to accept PRs if anyone can repro and fix, but I don't have any other machines that I can test with at this time.

**Comment by unadlib** [comment]
This is a misunderstanding. The Chrome on my Mac has GPU acceleration turned off.

**Comment by paularmstrong** [comment]
Whoops that'd do it!

Out of curiosity, do you have it off for a reason? Is this common?
